openapi: 3.0.3
info:
  title: Simple SSE API
  description: This API streams real-time data to clients using Server-Sent Events (SSE).
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
    description: Development server
paths:
  /stream:
    get:
      summary: Streams real-time data to the client
      description: Connects to the server to receive real-time data updates using Server-Sent Events (SSE).
      operationId: streamRealTimeData
      responses:
        '200':
          description: A continuous stream of data events.
          content:
            text/event-stream:
              schema:
                type: string
                example: "data:{'time': '2024-03-05 12:34:56', 'value': 1615123456.123}\n\n"
      x-summary: Stream Endpoint
components:
  schemas:
    Event:
      type: object
      properties:
        time:
          type: string
          format: date-time
          description: The server time when the event was generated.
        value:
          type: number
          format: float
          description: A floating point number representing the value at the given time.
